/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  InterestRateModel,
  InterestRateModelInterface,
} from "../InterestRateModel";

const _abi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_baseRatePerYear",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_slopePerYear",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "baseRatePerYear",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBorrowRatePerSecond",
    inputs: [
      {
        name: "totalCash",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalBorrows",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBorrowRatePerYear",
    inputs: [
      {
        name: "totalCash",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "totalBorrows",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "slopePerYear",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "view",
  },
] as const;

export class InterestRateModel__factory {
  static readonly abi = _abi;
  static createInterface(): InterestRateModelInterface {
    return new Interface(_abi) as InterestRateModelInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): InterestRateModel {
    return new Contract(address, _abi, runner) as unknown as InterestRateModel;
  }
}
