/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface InterestRateModelInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "baseRatePerYear"
      | "getBorrowRatePerSecond"
      | "getBorrowRatePerYear"
      | "slopePerYear"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "baseRatePerYear",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowRatePerSecond",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBorrowRatePerYear",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "slopePerYear",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "baseRatePerYear",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowRatePerSecond",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBorrowRatePerYear",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "slopePerYear",
    data: BytesLike
  ): Result;
}

export interface InterestRateModel extends BaseContract {
  connect(runner?: ContractRunner | null): InterestRateModel;
  waitForDeployment(): Promise<this>;

  interface: InterestRateModelInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  baseRatePerYear: TypedContractMethod<[], [bigint], "view">;

  getBorrowRatePerSecond: TypedContractMethod<
    [totalCash: BigNumberish, totalBorrows: BigNumberish],
    [bigint],
    "view"
  >;

  getBorrowRatePerYear: TypedContractMethod<
    [totalCash: BigNumberish, totalBorrows: BigNumberish],
    [bigint],
    "view"
  >;

  slopePerYear: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "baseRatePerYear"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getBorrowRatePerSecond"
  ): TypedContractMethod<
    [totalCash: BigNumberish, totalBorrows: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBorrowRatePerYear"
  ): TypedContractMethod<
    [totalCash: BigNumberish, totalBorrows: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "slopePerYear"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
